#!/usr/bin/env bash
# Run one fuzz target. Needs nightly Rust and cargo-fuzz (`cargo install cargo-fuzz`).
#
#   fuzz/run.sh <target> <seconds> [extra libFuzzer flags, e.g. -jobs=2 -workers=2]
#
# Targets: config, decode_pure, decode_libjpeg, resize, smart_resize, whisper.
#
# Environment:
#   FUZZ_DIR  where corpora and crash artifacts go (default: fuzz/, git-ignored)
#   CLANG     a clang binary; when set, libjpeg-turbo's C code (mozjpeg-sys) is compiled with
#             AddressSanitizer and libFuzzer coverage, so decode_libjpeg is coverage-guided
#             inside the C decoder too. rustc's LLVM and clang should be close in version.
#
# The committed inputs in fuzz/regressions/<target>/ (minimized crashes, all fixed) are always
# replayed as part of the corpus. Seed corpora are generated by fuzz/make_seeds.py.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
target=$1
secs=$2
shift 2
if [ -n "${CLANG:-}" ]; then
  export CC="$CLANG"
  export CFLAGS="-fsanitize=address -fsanitize-coverage=inline-8bit-counters,pc-table,trace-cmp -g -O1"
fi
dir=${FUZZ_DIR:-$PWD}
mkdir -p "$dir/corpus/$target" "$dir/artifacts/$target" "regressions/$target"
dict=()
[ -f "dicts/$target.dict" ] && dict=(-dict="dicts/$target.dict")
# The host triple explicitly: a prebuilt (musl) cargo-fuzz would otherwise default to its own.
host=$(rustc +nightly -vV | sed -n "s/^host: //p")
exec cargo +nightly fuzz run --target "$host" "$target" "$dir/corpus/$target" "regressions/$target" -- \
  -artifact_prefix="$dir/artifacts/$target/" -max_total_time="$secs" -rss_limit_mb=2048 -timeout=10 \
  "${dict[@]}" "$@"
