"""Write the licenses of the Rust crates compiled into the Python extension.

    python scripts/rust_dep_licenses.py > bindings/python/licenses/rust-dependencies.txt

Walks `cargo metadata` from the `hf-processors-py` package along normal (linked) dependencies
for all platforms, skipping proc-macro crates (they run at compile time and are not linked)
and the workspace's own crates. For every crate it records the declared SPDX license and the
license / notice files shipped in the crate, de-duplicating identical texts. libjpeg-turbo (C,
inside mozjpeg-sys) has its own files next to this one. CI checks the output is up to date.
"""

import hashlib
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LICENSE_PREFIXES = ("license", "licence", "copying", "notice", "copyright", "unlicense")


def main():
    meta = json.loads(subprocess.check_output(
        ["cargo", "metadata", "--format-version", "1", "--locked", "--manifest-path", str(ROOT / "Cargo.toml")]))
    pkgs = {p["id"]: p for p in meta["packages"]}
    nodes = {n["id"]: n for n in meta["resolve"]["nodes"]}
    workspace = set(meta["workspace_members"])
    start = next(i for i in workspace if pkgs[i]["name"] == "hf-processors-py")
    seen, stack = set(), [start]
    while stack:
        cur = stack.pop()
        for dep in nodes[cur]["deps"]:
            if not any(k["kind"] is None for k in dep["dep_kinds"]):
                continue  # dev- or build-only
            p = pkgs[dep["pkg"]]
            if any("proc-macro" in t["kind"] for t in p["targets"]):
                continue
            if dep["pkg"] not in seen:
                seen.add(dep["pkg"])
                stack.append(dep["pkg"])
    crates = sorted((pkgs[i] for i in seen if i not in workspace), key=lambda p: (p["name"], p["version"]))

    texts = {}  # sha -> (text, [crate names])
    rows = []
    for p in crates:
        d = Path(p["manifest_path"]).parent
        files = sorted(f for f in d.iterdir() if f.is_file() and f.name.lower().startswith(LICENSE_PREFIXES))
        refs = []
        for f in files:
            t = f.read_text(encoding="utf-8", errors="replace").strip()
            h = hashlib.sha256(t.encode()).hexdigest()[:12]
            texts.setdefault(h, (t, []))[1].append(f"{p['name']} {p['version']} ({f.name})")
            refs.append(h)
        rows.append((p, refs))

    out = ["Rust crates compiled into the hf_processors_rs extension module",
           "=" * 64, "",
           "Generated by scripts/rust_dep_licenses.py from Cargo.lock. Each crate lists its declared",
           "license and the license texts it ships (by id; the texts follow). libjpeg-turbo's licenses",
           "are in libjpeg-turbo-LICENSE.md and libjpeg-turbo-README.ijg.", ""]
    for p, refs in rows:
        src = p.get("repository") or ""
        lic = p.get("license") or p.get("license_file") or "unspecified"
        ids = ", ".join(refs) if refs else "(the crate ships no license file)"
        out.append(f"- {p['name']} {p['version']}: {lic}; {src}; texts: {ids}")
    out += ["", ""]
    for h, (t, users) in sorted(texts.items(), key=lambda kv: kv[1][1][0]):
        out += ["-" * 79, f"[{h}] used by: " + "; ".join(users), "-" * 79, "", t, "", ""]
    print("\n".join(out).rstrip() + "\n", end="")


if __name__ == "__main__":
    main()
